export const CART_ADD_ITEM='CARD_ADD_ITEM'
export const CART_REMOVE_ITEM='CARD_REMOVE_ITEM'
export const CART_SAVE_SHIPPINGADDR='CART_SAVE_SIPPINGADDR'
export const CART_SAVE_PAYMENT= 'CART_SAVE_METHOD'
export const CART_CLEAR_ITEMS="CART_CLEAR_ITEMS"